export enum RegionalCouncilEnum {
    CRM = 1,
    CRMV = 2,
    CRP = 3,
    CREFITO = 4,
    CRN = 5,
    CRBM = 6,
    CRO = 7,
    COREN = 8,
    CRF = 9,
    CRFA = 10,
    CONREF = 11,
}

export const RegionalCouncilNameToId: {
    [x: string]: number;
} = {
    "CRM - Conselho Regional de Medicina": 1,
    "CRMV - Conselho Regional de Medicina Veterinária": 2,
    "CRP - Conselhos Regionais de Psicologia": 3,
    "CREFITO - Conselho Regional de Fisioterapia e Terapia Ocupacional": 4,
    "CRN - Conselho Regional de Nutricionistas": 5,
    "CRBM - Conselho Regional de Biomedicina": 6,
    "CRO – Conselho Regional de Odontologia": 7,
    "COREN – Conselho Regional de Enfermagem": 8,
    "CRF – Conselho Federal de Farmácias": 9,
    "CRFA – Conselho Federal de Fonoaudiologia": 10,
    "CONREF – Conselho Federal de Educação Física": 11,
};

export const RegionalCouncilIdToName: {
    [x: number]: string;
} = {
    1: "CRM - Conselho Regional de Medicina",
    2: "CRMV - Conselho Regional de Medicina Veterinária",
    3: "CRP - Conselhos Regionais de Psicologia",
    4: "CREFITO - Conselho Regional de Fisioterapia e Terapia Ocupacional",
    5: "CRN - Conselho Regional de Nutricionistas",
    6: "CRBM - Conselho Regional de Biomedicina",
    7: "CRO – Conselho Regional de Odontologia",
    8: "COREN – Conselho Regional de Enfermagem",
    9: "CRF – Conselho Federal de Farmácias",
    10: "CRFA – Conselho Federal de Fonoaudiologia",
    11: "CONREF – Conselho Federal de Educação Física",
};

export const RegionalCouncilIdToAcronym: {
    [x: number]: string;
} = {
    1: "CRM",
    2: "CRMV",
    3: "CRP",
    4: "CREFITO",
    5: "CRN",
    6: "CRBM",
    7: "CRO",
    8: "COREN",
    9: "CRF",
    10: "CRFA",
    11: "CONREF",
};

export const RegionalCouncilList = [
    "CRM - Conselho Regional de Medicina",
    "CRMV - Conselho Regional de Medicina Veterinária",
    "CRP - Conselhos Regionais de Psicologia",
    "CREFITO - Conselho Regional de Fisioterapia e Terapia Ocupacional",
    "CRN - Conselho Regional de Nutricionistas",
    "CRBM - Conselho Regional de Biomedicina",
    "CRO – Conselho Regional de Odontologia",
    "COREN – Conselho Regional de Enfermagem",
    "CRF – Conselho Federal de Farmácias",
    "CRFA – Conselho Federal de Fonoaudiologia",
    "CONREF – Conselho Federal de Educação Física",
];

export const specilityByCouncil: { [x: string]: string[] } = {
    "CRM - Conselho Regional de Medicina": [
        "Acupuntura",
        "Alergia e imunologia",
        "Anestesiologia",
        "Angiologia",
        "Cardiologia",
        "Cirurgia cardiovascular",
        "Cirurgia da mão",
        "Cirurgia de cabeça e pescoço",
        "Cirurgia do aparelho digestivo",
        "Cirurgia geral",
        "Cirurgia oncológica",
        "Cirurgia pediátrica",
        "Cirurgia plástica",
        "Cirurgia torácica",
        "Cirurgia vascular",
        "Clínica médica",
        "Coloproctologia",
        "Dermatologia",
        "Endocrinologia e metabologia",
        "Endoscopia",
        "Gastroenterologia",
        "Genética médica",
        "Geriatria",
        "Ginecologia e obstetrícia",
        "Hematologia e hemoterapia",
        "Homeopatia",
        "Infectologia",
        "Mastologia",
        "Medicina de emergência",
        "Medicina de família e comunidade",
        "Medicina do trabalho",
        "Medicina de tráfego",
        "Medicina esportiva",
        "Medicina física e reabilitação",
        "Medicina intensiva",
        "Medicina legal e perícia médica",
        "Medicina nuclear",
        "Medicina preventiva e social",
        "Nefrologia",
        "Neurocirurgia",
        "Neurologia",
        "Nutrologia",
        "Oftalmologia",
        "Oncologia clínica",
        "Ortopedia e traumatologia",
        "Otorrinolaringologia",
        "Patologia",
        "Patologia clínica/medicina laboratorial",
        "Pediatria",
        "Pneumologia",
        "Psiquiatria",
        "Radiologia e diagnóstico por imagem",
        "Radioterapia",
        "Reumatologia",
        "Urologia",
    ],
    "CRMV - Conselho Regional de Medicina Veterinária": [
        "Acupuntura Veterinária",
        "Anestesiologia Veterinária",
        "Cardiologia Veterinária",
        "Cirurgia Veterinária",
        "Clínica Médica de Pequenos Animais",
        "Dermatologia Veterinária",
        "Diagnóstico por Imagem na Medicina Veterinária",
        "Endocrinologia Veterinária",
        "Homeopatia Veterinária",
        "Inspeção Higiênica, Sanitária e Tecnológica de Produtos Animais",
        "Medicina de Animais Selvagens",
        "Medicina Felina",
        "Medicina Veterinária Intensiva",
        "Medicina Veterinária do Coletivo",
        "Nutrição de Cães e Gatos (médicos-veterinários e zootecnistas)",
        "Oftalmologia Veterinária",
        "Oncologia Veterinária",
        "Patologia Veterinária",
    ],
    "CRP - Conselhos Regionais de Psicologia": [
        "Psicologia Escolar/Educacional",
        "Psicologia Organizacional e do Trabalho",
        "Psicologia de Trânsito",
        "Psicologia Jurídica",
        "Psicologia do Esporte",
        "Psicologia Clínica",
        "Psicologia Hospitalar",
        "Psicopedagogia",
        "Psicomotricidade",
        "Psicologia Social",
        "Neuropsicologia",
        "Psicologia em Saúde",
        "Avaliação Psicológica",
    ],
    "CREFITO - Conselho Regional de Fisioterapia e Terapia Ocupacional": [
        "Fisioterapia em Acupuntura",
        "Fisioterapia aquática",
        "Fisioterapia cardiovascular",
        "Fisioterapia Dermato funcional",
        "Fisioterapia esportiva",
        "Fisioterapia em gerontologia",
        "Fisioterapia do trabalho",
        "Fisioterapia neuro funcional",
        "Fisioterapia em oncologia",
        "Fisioterapia respiratória",
        "Fisioterapia Traumato-ortopédica",
        "Fisioterapia em osteopatia",
        "Fisioterapia em quiropraxia",
        "Fisioterapia em saúde da mulher",
        "Fisioterapia em terapia intensiva",
    ],
    "CRN - Conselho Regional de Nutricionistas": [
        "Educação alimentar e nutricional",
        "Gestão de políticas públicas e programas em alimentação e nutrição",
        "Nutrição clínica",
        "Nutrição clínica em cardiologia",
        "Nutrição clínica em cuidados paliativos",
        "Nutrição clínica em endocrinologia e metabologia",
        "Nutrição clínica em gastroenterologia",
        "Nutrição clínica em gerontologia",
        "Nutrição clínica em nefrologia",
        "Nutrição clínica em oncologia",
        "Nutrição clínica em terapia intensiva",
        "Nutrição de precisão",
        "Nutrição e alimentos funcionais",
        "Nutrição e fitoterapia",
        "Nutrição em alimentação coletiva",
        "Nutrição em alimentação coletiva hospitalar",
        "Nutrição em alimentação escolar",
        "Nutrição em atenção primária e saúde da família e comunidade",
        "Nutrição em esportes e exercício físico",
        "Nutrição em estética",
        "Nutrição em marketing",
        "Nutrição em saúde coletiva",
        "Nutrição em saúde da mulher",
        "Nutrição em saúde de povos e comunidades tradicionais",
        "Nutrição em saúde indígena",
        "Nutrição em saúde mental",
        "Nutrição em transtornos alimentares",
        "Nutrição em vegetarianismo e veganismo",
        "Nutrição materno-infantil",
        "Nutrição na produção de refeições comerciais",
        "Nutrição na produção da tecnologia de alimentos e bebidas",
        "Qualidade e segurança dos alimentos",
        "Segurança alimentar e nutricional",
        "Terapia de nutrição enteral e parenteral",
    ],
    "CRBM - Conselho Regional de Biomedicina": [
        "Acupuntura",
        "Análise Ambiental",
        "Análises Bromatológicas",
        "Auditoria",
        "Banco de Sangue",
        "Biofísica",
        "Biologia Molecular",
        "Biomedicina Estética",
        "Bioquímica",
        "Citologia Oncótica",
        "Embriologia",
        "Farmacologia",
        "Fisiologia",
        "Fisiologia Geral",
        "Fisiologia Humana",
        "Genética",
        "Hematologia",
        "Histologia Humana",
        "Histotecnologia Clínica",
        "Imunologia",
        "Imagenologia (exceto interpretação)",
        "Informática de Saúde",
        "Microbiologia",
        "Microbiologia de Alimentos",
        "Monitoramento Neurofisiológico Transoperatório",
        "Parasitologia",
        "Patologia",
        "Patologia Clínica (Análises Clínicas)",
        "Perfusão",
        "Psicobiologia",
        "Radiologia",
        "Reprodução Humana",
        "Sanitarista",
        "Saúde Pública",
        "Toxicologia",
        "Virologia",
    ],
    "CRO – Conselho Regional de Odontologia": [
        "Cirurgia e Traumatologia Buco-Maxilo-Faciais",
        "Clínica Geral",
        "Dentística",
        "Disfunção Temporomandibular e Dor Orofacial",
        "Endodontia",
        "Estomatologia",
        "Harmonização Orofacial",
        "Radiologia Odontológica e Imaginologia",
        "Implantodontia",
        "Odontologia Legal",
        "Odontologia do Trabalho",
        "Odontologia para Pacientes com Necessidades Especiais",
        "Odontogeriatria",
        "Odontopediatria",
        "Ortodontia",
        "Ortopedia Funcional dos Maxilares",
        "Patologia Bucal",
        "Periodontia",
        "Prótese Buco-Maxilo-Facial",
        "Prótese Dentária",
        "Saúde Coletiva e da Família",
    ],
    "COREN – Conselho Regional de Enfermagem": [
        "Enfermagem Aeroespacial",
        "Enfermagem Aquaviária",
        "Enfermagem em Acesso Vascular e Terapia Infusional",
        "Assistência de Enfermagem em Anestesiologia",
        "Enfermagem em Assistência Domiciliária",
        "Enfermagem em Captação, Doação e Transplante de Órgãos e Tecidos",
        "Enfermagem em Cardiologia",
        "Enfermagem em Central de Material e Esterilização",
        "Enfermagem em Centro Cirúrgico",
        "Enfermagem em Cuidados Paliativos",
        "Enfermagem Dermatológica",
        "Enfermagem em Diagnóstico por Imagens",
        "Enfermagem em Doenças Infecciosas e Parasitárias",
        "Enfermagem em Endocrinologia",
        "Enfermagem em Estética",
        "Enfermagem em Estomaterapia",
        "Enfermagem em Farmacologia",
        "Enfermagem Forense",
        "Enfermagem em Genética e Genâmica",
        "Enfermagem em Hematologia",
        "Enfermagem em Hemoterapia",
        "Enfermagem Hiperbárica",
        "Enfermagem no Manejo da Dor",
        "Enfermagem em Nefrologia",
        "Enfermagem em Neurologia e Neurocirurgia",
        "Enfermagem Offshore",
        "Enfermagem em Oftalmologia",
        "Enfermagem em Oncologia ",
        "Enfermagem em Otorrinolaringologia",
        "Enfermagem em Práticas Integrativas e Complementares",
        "Enfermagem em Prevenção e Controle de Infecção Hospitalar",
        "Enfermagem em Saúde da Criança e Adolescente",
        "Enfermagem em Saúde Coletiva",
        "Enfermagem em Saúde da Mulher",
        "Enfermagem em Saúde do Adulto",
        "Enfermagem em Saúde do Homem",
        "Enfermagem em Saúde do Idoso",
        "Enfermagem em Saúde do Trabalhador ",
        "Enfermagem em Saúde Indígena",
        "Enfermagem em Saúde Mental ",
        "Enfermagem em Sexologia Humana",
        "Enfermagem em Sistematização da Assistência da Enfermagem-SAE",
        "Enfermagem em Terapia Intensiva",
        "Enfermagem em Terapia Nutricional e Nutrição Clínica",
        "Enfermagem em Traumato-ortopedia",
        "Enfermagem em Urgência e Emergência",
        "Enfermagem em Urologia",
        "Enfermagem em Vigilância",
        "Enfermagem - Gestão",
        "Enfermagem - Ensino e Pesquisa",
    ],
    "CRF – Conselho Regional de Farmácias": [
        "Alimentos funcionais e nutracêuticos",
        "Análises clínicas",
        "Análises toxicológicas",
        "Antroposofia",
        "Assistência farmacêutica",
        "Assuntos regulatórios",
        "Atenção farmacêutica",
        "Atenção farmacêutica domiciliar",
        "Atendimento farmacêutico de urgência e emergência",
        "Auditoria em saúde",
        "Avaliação de tecnologia em saúde",
        "Bacteriologia clínica",
        "Banco de leite humano",
        "Banco de materiais biológicos",
        "Banco de órgãos, tecidos e células",
        "Banco de sangue",
        "Banco de sêmen",
        "Biofarmácia",
        "Biologia molecular",
        "Bioquímica clínica",
        "Biotecnologia industrial",
        "Citogenética",
        "Citologia clínica",
        "Citopatologia",
        "Citoquímica",
        "Controle de qualidade",
        "Controle de qualidade de alimentos",
        "Controle de qualidade e tratamento de água",
        "Controle de vetores e pragas urbanas",
        "Cultura celular",
        "Dispensação",
        "Docência do ensino superior",
        "Educação ambiental",
        "Educação em saúde",
        "Empreendedorismo",
        "Epidemiologia genética",
        "Estratégia Saúde da Família (ESF)",
        "Farmácia clínica domiciliar",
        "Farmácia clínica em cardiologia",
        "Farmácia clínica em cuidados paliativos",
        "Farmácia clínica em geriatria",
        "Farmácia clínica em hematologia",
        "Farmácia clínica em oncologia",
        "Farmácia clínica em pediatria",
        "Farmácia clínica em reumatologia",
        "Farmácia clínica em terapia antineoplásica",
        "Farmácia clínica em unidades de terapia intensiva",
        "Farmácia clínica hospitalar",
        "Farmácia comunitária",
        "Farmácia hospitalar e outros serviços de saúde",
        "Farmácia magistral",
        "Farmácia oncológica",
        "Farmácia veterinária",
        "Farmacocinética clínica",
        "Farmacoeconomia",
        "Farmacoepidemiologia",
        "Farmacogenética",
        "Farmacogenômica",
        "Farmacologia clínica",
        "Farmacovigilância",
        "Garantia da qualidade",
        "Gases e misturas de uso terapêutico",
        "Genética",
        "Gerenciamento dos resíduos em serviços de saúde",
        "Gestão ambiental",
        "Gestão da assistência farmacêutica",
        "Gestão da qualidade",
        "Gestão de farmácias e drogarias",
        "Gestão de risco hospitalar",
        "Gestão e controle de laboratório clínico",
        "Gestão em saúde pública",
        "Gestão farmacêutica",
        "Gestão hospitalar",
        "Hematologia clínica",
        "Hemoderivados",
        "Hemoterapia",
        "Histocompatibilidade",
        "Histoquímica",
        "Homeopatia",
        "Imunocitoquímica",
        "Imunogenética",
        "Imunohistoquímica",
        "Imunologia clínica",
        "Imunopatologia",
        "Indústria de cosméticos",
        "Indústria de farmoquímicos",
        "Indústria de saneantes",
        "Indústria farmacêutica e de insumos farmacêuticos",
        "Logística farmacêutica",
        "Marketing farmacêutico",
        "Medicina tradicional chinesa-acupuntura",
        "Metodologia de ensino superior",
        "Micologia clínica",
        "Microbiologia clínica",
        "Microbiologia de alimentos",
        "Nanotecnologia",
        "Nutrição enteral",
        "Nutrição parenteral",
        "Nutrigenômica",
        "Parasitologia clínica",
        "Pesquisa clínica",
        "Pesquisa e desenvolvimento",
        "Pesquisa e desenvolvimento de alimentos",
        "Planejamento e gestão educacional",
        "Plantas medicinais e fitoterapia",
        "Produção de alimentos",
        "Radiofarmácia",
        "Reprodução humana",
        "Saúde ambiental",
        "Saúde coletiva",
        "Saúde do trabalhador",
        "Saúde ocupacional",
        "Segurança no trabalho",
        "Tecnologia de fermentação",
        "Termalismo social/crenoterapia",
        "Toxicogenética",
        "Toxicologia ambiental",
        "Toxicologia analítica",
        "Toxicologia clínica",
        "Toxicologia de alimentos",
        "Toxicologia de cosméticos",
        "Toxicologia de emergência",
        "Toxicologia de medicamentos",
        "Toxicologia desportiva",
        "Toxicologia experimental",
        "Toxicologia forense",
        "Toxicologia ocupacional",
        "Toxicologia veterinária",
        "Vigilância epidemiológica",
        "Vigilância sanitária",
        "Virologia clínica",
        "Floralterapia",
        "Perfusão sanguínea",
        "Saúde Estética",
        "Vacinação",
    ],
    "CONREF – Conselho Regional de Educação Física": [
        "Saúde Coletiva",
        "Saúde Mental",
        "Saúde da Família",
        "Educação Física Escolar",
        "Fisiologia do Exercício e do Esporte",
        "Desportos Aquáticos",
        "Treinamento Resistido/Musculação",
        "Biomecânica do Exercício",
        "Ginástica Laboral",
        "Ginásticas Esportivas",
        "Esporte",
        "Treinamento Esportivo/Físico",
        "Avaliação Física",
        "Pilates",
        "Psicomotricidade",
        "Cardiovascular",
        "Hidroginástica",
    ],
    "CRFA – Conselho Regional de Fonoaudiologia": [
        "Audiologia",
        "Linguagem",
        "Motricidade Orofacial",
        "Saúde Coletiva",
        "Voz",
        "Disfagia",
        "Fonoaudiologia Educacional",
        "Gerontologia",
        "Fonoaudiologia Neurofuncional",
        "Fonoaudiologia do Trabalho",
        "Neuropsicologia",
        "Fluência",
        "Perícia Fonoaudiológica",
        "Fonoaudiologia Hospitalar",
    ],
};
