export const especialities = [
    "Acupuntura",
    "Administração em saúde",
    "Alergia e imunologia",
    "Alergia e imunologia pediátrica",
    "Anestesiologia",
    "Angiologia",
    "Angiorradiologia e cirurgia endovascular",
    "Atendimento ao queimado",
    "Cardiologia",
    "Cardiologia pediátrica",
    "Cirurgia bariátrica",
    "Cirurgia cardiovascular",
    "Cirurgia crânio-maxilo-facial",
    "Cirurgia da mão",
    "Cirurgia de cabeça e pescoço",
    "Cirurgia do aparelho digestivo",
    "Cirurgia do trauma",
    "Cirurgia geral",
    "Cirurgia oncológica",
    "Cirurgia pediátrica",
    "Cirurgia plástica",
    "Cirurgia torácica",
    "Cirurgia vascular",
    "Cirurgia videolaparoscópica",
    "Citopatologia",
    "Clínica médica",
    "Coloproctologia",
    "Densitometria óssea",
    "Dermatologia",
    "Dor",
    "Ecocardiografia",
    "Ecografia vascular com doppler",
    "Eletrofisiologia clínica invasiva",
    "Emergência pediátrica",
    "Endocrinologia e metabologia",
    "Endocrinologia pediátrica",
    "Endoscopia",
    "Endoscopia digestiva",
    "Endoscopia ginecológica",
    "Endoscopia respiratória",
    "Ergometria",
    "Estimulação cardíaca eletrônica implantável",
    "Foniatria",
    "Gastroenterologia",
    "Gastroenterologia pediátrica",
    "Genética médica",
    "Geriatria",
    "Ginecologia e obstetrícia",
    "Hansenologia",
    "Hematologia e hemoterapia",
    "Hematologia e hemoterapia pediátrica",
    "Hemodinâmica e cardiologia intervencionista",
    "Hepatologia",
    "Homeopatia",
    "Infectologia",
    "Infectologia hospitalar",
    "Infectologia pediátrica",
    "Mamografia",
    "Mastologia",
    "Medicina aeroespacial",
    "Medicina de emergência",
    "Medicina de família e comunidade",
    "Medicina de tráfego",
    "Medicina do adolescente",
    "Medicina do sono",
    "Medicina do trabalho",
    "Medicina esportiva",
    "Medicina fetal",
    "Medicina física e reabilitação",
    "Medicina intensiva",
    "Medicina intensiva pediátrica",
    "Medicina legal e perícia médica",
    "Medicina nuclear",
    "Medicina paliativa",
    "Medicina preventiva e social",
    "Medicina tropical",
    "Nefrologia",
    "Nefrologia pediátrica",
    "Neonatologia",
    "Neurocirurgia",
    "Neurofisiologia clínica",
    "Neurologia",
    "Neurologia pediátrica",
    "Neurorradiologia",
    "Nutrição parenteral e enteral",
    "Nutrição parenteral e enteral pediátrica",
    "Nutrologia",
    "Nutrologia pediátrica",
    "Oftalmologia",
    "Oncologia clínica",
    "Oncologia pediátrica",
    "Ortopedia e traumatologia",
    "Otorrinolaringologia",
    "Patologia",
    "Patologia clínica/medicina laboratorial",
    "Pediatria",
    "Pneumologia",
    "Pneumologia pediátrica",
    "Psicogeriatria",
    "Psicoterapia",
    "Psiquiatria",
    "Psiquiatria da infância e adolescência",
    "Psiquiatria forense",
    "Radiologia e diagnóstico por imagem",
    "Radiologia intervencionista e angiorradiologia",
    "Radioterapia",
    "Reprodução assistida",
    "Reumatologia",
    "Reumatologia pediátrica",
    "Sexologia",
    "Toxicologia médica",
    "Transplante de medula óssea",
    "Ultrassonografia em ginecologia e obstetrícia",
    "Urologia",
];
